export const filename: { readonly [key: string]: string } = {
  "Airburst Rocket Launcher": "blue/Airburst Rocket Launcher.svg",
  "Anti-Materiel Rifle": "blue/Anti-Materiel Rifle.svg",
  "Anti-Personnel Minefield": "green/Anti-Personnel Minefield.svg",
  "Anti-Tank Emplacement": "green/Anti-Tank Emplacement.svg",
  "Anti-Tank Mines": "green/Anti-Tank Mines.svg",
  "Arc Thrower": "blue/Arc Thrower.svg",
  "Autocannon Sentry": "green/Autocannon Sentry.svg",
  "Autocannon": "blue/Autocannon.svg",
  "Ballistic Shield Backpack": "blue/Ballistic Shield Backpack.svg",
  "Commando": "blue/Commando.svg",
  "Directional Shield": "blue/Directional Shield.svg",
  "Eagle 110MM Rocket Pods": "red/Eagle 110MM Rocket Pods.svg",
  "Eagle 500KG Bomb": "red/Eagle 500KG Bomb.svg",
  "Eagle Airstrike": "red/Eagle Airstrike.svg",
  "Eagle Cluster Bomb": "red/Eagle Cluster Bomb.svg",
  "Eagle Napalm Airstrike": "red/Eagle Napalm Airstrike.svg",
  "Eagle Smoke Strike": "red/Eagle Smoke Strike.svg",
  "Eagle Strafing Run": "red/Eagle Strafing Run.svg",
  "EMS Mortar Sentry": "green/EMS Mortar Sentry.svg",
  "Emancipator Exosuit": "blue/Emancipator Exosuit.svg",
  "Epoch": "blue/Epoch.svg",
  "Expendable Anti-Tank": "blue/Expendable Anti-Tank.svg",
  "Expendable Napalm": "blue/Expendable Napalm.svg",
  "Fast Recon Vehicle": "blue/Fast Recon Vehicle.svg",
  "Flame Sentry": "green/Flame Sentry.svg",
  "Flamethrower": "blue/Flamethrower.svg",
  "GL-52 De-Escalator": "blue/GL-52 De-Escalator.svg",
  "Gas Mine": "green/Gas Mine.svg",
  "Gatling Sentry": "green/Gatling Sentry.svg",
  "Grenade Launcher": "blue/Grenade Launcher.svg",
  "Grenadier Battlement": "green/Grenadier Battlement.svg",
  "Guard Dog Breath": "blue/Guard Dog Breath.svg",
  "Guard Dog K-9": "blue/Guard Dog K-9.svg",
  "Guard Dog Rover": "blue/Guard Dog Rover.svg",
  "Guard Dog": "blue/Guard Dog.svg",
  "HMG Emplacement": "green/HMG Emplacement.svg",
  "Heavy Machine Gun": "blue/Heavy Machine Gun.svg",
  "Hellbomb Portable": "blue/Hellbomb Portable.svg",
  "Hover Pack": "blue/Hover Pack.svg",
  "Incendiary Mines": "green/Incendiary Mines.svg",
  "Jump Pack": "blue/Jump Pack.svg",
  "Laser Cannon": "blue/Laser Cannon.svg",
  "Laser Sentry": "green/Laser Sentry.svg",
  "Machine Gun Sentry": "green/Machine Gun Sentry.svg",
  "Machine Gun": "blue/Machine Gun.svg",
  "Mortar Sentry": "green/Mortar Sentry.svg",
  "One True Flag": "blue/One True Flag.svg",
  "Orbital 120MM HE Barrage": "red/Orbital 120MM HE Barrage.svg",
  "Orbital 380MM HE Barrage": "red/Orbital 380MM HE Barrage.svg",
  "Orbital Airburst Strike": "red/Orbital Airburst Strike.svg",
  "Orbital EMS Strike": "red/Orbital EMS Strike.svg",
  "Orbital Gas Strike": "red/Orbital Gas Strike.svg",
  "Orbital Gatling Barrage": "red/Orbital Gatling Barrage.svg",
  "Orbital Laser": "red/Orbital Laser.svg",
  "Orbital Napalm Barrage": "red/Orbital Napalm Barrage.svg",
  "Orbital Precision Strike": "red/Orbital Precision Strike.svg",
  "Orbital Railcannon Strike": "red/Orbital Railcannon Strike.svg",
  "Orbital Smoke Strike": "red/Orbital Smoke Strike.svg",
  "Orbital Walking Barrage": "red/Orbital Walking Barrage.svg",
  "Patriot Exosuit": "blue/Patriot Exosuit.svg",
  "Quasar Cannon": "blue/Quasar Cannon.svg",
  "Railgun": "blue/Railgun.svg",
  "Recoilless Rifle": "blue/Recoilless Rifle.svg",
  "Rocket Sentry": "green/Rocket Sentry.svg",
  "Shield Generator Pack": "blue/Shield Generator Pack.svg",
  "Shield Generator Relay": "green/Shield Generator Relay.svg",
  "Solo Silo": "blue/Solo Silo.svg",
  "Spear": "blue/Spear.svg",
  "Speargun": "blue/Speargun.svg",
  "StA-X3 WASP Launcher": "blue/StA-X3 W.A.S.P. Launcher.svg",
  "Stalwart": "blue/Stalwart.svg",
  "Sterilizer": "blue/Sterilizer.svg",
  "Supply Pack": "blue/Supply Pack.svg",
  "Tesla Tower": "green/Tesla Tower.svg",
  "Warp Pack": "blue/Warp Pack.svg"
};
