export const stratagemName: { readonly [key: string]: string } = {
  ad334guarddog: "「护卫犬」",
  axlas5guarddogrover: "「护卫犬」漫游车",
  axtx13guarddogdogbreath: "「护卫犬」腐息",
  b1supplypack: "补给背包",
  guarddogarc: "「护卫犬」K-9",
  lift850jumppack: "喷射背包",
  lift860hoverpack: "悬浮背包",
  portablehellbomb: "便携式地狱火炸弹",
  sh20ballisticshieldbackpack: "防弹护盾背包",
  sh20shieldgeneratorpack: "防护罩生成包",
  sh51directionalshield: "定向护盾",
  warppack: "传送背包",
  ac8autocannon: "机炮",
  apw1antimaterielrifle: "反器材步枪",
  arc3arcthrower: "电弧发射器",
  eat17expendableantitank: "消耗性反坦克武器",
  epoch: "纪元",
  faf14spear: "飞矛",
  flam40flamethrower: "火焰喷射器",
  gl21grenadelauncher: "榴弹发射器",
  gl52deescalator: "缓和使者",
  gr8recoillessrifle: "无后坐力炮",
  las98lasercannon: "激光大炮",
  las99quasarcannon: "类星体",
  m105stalwart: "盟友",
  mg206heavymachinegun: "重机枪",
  mg43machinegun: "机枪",
  mls4xcommandorocketlauncher: "突击兵",
  onetrueflag: "唯一真旗",
  rl77airburstrocketlauncher: "空爆火箭弹发射器",
  rs422railgun: "磁轨炮",
  tx41sterilizer: "灭菌器",
  wasplauncher: "WASP 发射器",
  exo45patriotexosuit: "爱国者机甲",
  exo49emancipatorexosuit: "解放者机甲",
  fastreconvehicle: "快速侦察载具",
  antipersonnelminefield: "反步兵地雷",
  antitankmines: "反坦克地雷",
  gasmines: "毒气地雷",
  incendiarymines: "燃烧地雷",
  aflam40flamesentry: "火焰喷射哨戒炮",
  autocannonsentry: "自动哨戒炮",
  eat12antitankemplacement: "反坦克炮台",
  emsmortarsentry: "电磁迫击炮",
  gatlingsentry: "加特林炮台",
  grenadierbattlement: "掷弹兵防卫墙",
  hmgemplacement: "重机枪部署支架",
  lasersentry: "激光哨戒炮",
  machinegunsentry: "哨戒机枪",
  mortarsentry: "迫击哨戒炮",
  rocketsentry: "火箭哨戒炮",
  shieldgeneratorrelay: "防护罩生成中继器",
  teslatower: "特斯拉塔",
  eagle110mmrocketpods: "「飞鹰」110MM 火箭巢",
  eagle500kgbomb: "「飞鹰」500KG 炸弹",
  eagleairstrike: "「飞鹰」空袭",
  eagleclusterbomb: "「飞鹰」集束炸弹",
  eaglenapalmstrike: "「飞鹰」凝固汽油弹空袭",
  eaglesmokestrike: "「飞鹰」烟雾攻击",
  eaglestrafingrun: "「飞鹰」机枪扫射",
  orbital120mmhebarrage: "轨道 120MM 高爆弹火力网",
  orbital380mmhebarrage: "轨道 380MM 高爆弹火力网",
  orbitalairburststrike: "轨道空爆攻击",
  orbitalemsstrike: "轨道电磁冲击波攻击",
  orbitalgasstrike: "轨道毒气攻击",
  orbitalgatlingbarrage: "轨道加特林火力网",
  orbitallaser: "轨道激光炮",
  orbitalnapalmbarrage: "轨道凝固汽油弹火力网",
  orbitalprecisionstrike: "轨道精准攻击",
  orbitalrailcannonstrike: "轨道磁轨炮攻击",
  orbitalsmokestrike: "轨道烟雾攻击",
  orbitalwalkingbarrage: "轨道游走火力网",
};
