export const backpack: readonly string[] = [
  "Ballistic Shield Backpack",
  "Directional Shield",
  "Guard Dog Breath",
  "Guard Dog K-9",
  "Guard Dog Rover",
  "Guard Dog",
  "Hellbomb Portable",
  "Hover Pack",
  "Jump Pack",
  "Shield Generator Pack",
  "Supply Pack",
  "Warp Pack"
];

export const supportWeapon: readonly string[] = [
  "Airburst Rocket Launcher",
  "Anti-Materiel Rifle",
  "Arc Thrower",
  "Autocannon",
  "Commando",
  "Epoch",
  "Expendable Anti-Tank",
  "Expendable Napalm",
  "GL-52 De-Escalator",
  "Grenade Launcher",
  "Heavy Machine Gun",
  "Laser Cannon",
  "Machine Gun",
  "One True Flag",
  "Quasar Cannon",
  "Railgun",
  "Recoilless Rifle",
  "Solo Silo",
  "Spear",
  "Speargun",
  "StA-X3 WASP Launcher",
  "Stalwart",
  "Sterilizer"
];

export const supportWeaponWithBackpack: readonly string[] = [
  "Airburst Rocket Launcher",
  "Autocannon",
  "Recoilless Rifle",
  "Spear",
  "StA-X3 WASP Launcher"
];

export const attack: readonly string[] = [
  "Eagle 110MM Rocket Pods",
  "Eagle 500KG Bomb",
  "Eagle Airstrike",
  "Eagle Cluster Bomb",
  "Eagle Napalm Airstrike",
  "Eagle Smoke Strike",
  "Eagle Strafing Run",
  "Orbital 120MM HE Barrage",
  "Orbital 380MM HE Barrage",
  "Orbital Airburst Strike",
  "Orbital EMS Strike",
  "Orbital Gas Strike",
  "Orbital Gatling Barrage",
  "Orbital Laser",
  "Orbital Napalm Barrage",
  "Orbital Precision Strike",
  "Orbital Railcannon Strike",
  "Orbital Smoke Strike",
  "Orbital Walking Barrage"
];

export const support: readonly string[] = [
  "Airburst Rocket Launcher",
  "Anti-Materiel Rifle",
  "Arc Thrower",
  "Autocannon",
  "Ballistic Shield Backpack",
  "Commando",
  "Directional Shield",
  "Emancipator Exosuit",
  "Epoch",
  "Expendable Anti-Tank",
  "Expendable Napalm",
  "Fast Recon Vehicle",
  "Flamethrower",
  "GL-52 De-Escalator",
  "Grenade Launcher",
  "Guard Dog Breath",
  "Guard Dog K-9",
  "Guard Dog Rover",
  "Guard Dog",
  "Heavy Machine Gun",
  "Hellbomb Portable",
  "Hover Pack",
  "Jump Pack",
  "Laser Cannon",
  "Machine Gun",
  "One True Flag",
  "Patriot Exosuit",
  "Quasar Cannon",
  "Railgun",
  "Recoilless Rifle",
  "Shield Generator Pack",
  "Solo Silo",
  "Spear",
  "Speargun",
  "StA-X3 WASP Launcher",
  "Stalwart",
  "Sterilizer",
  "Supply Pack",
  "Warp Pack"
];

export const defense: readonly string[] = [
  "Anti-Personnel Minefield",
  "Anti-Tank Emplacement",
  "Anti-Tank Mines",
  "Autocannon Sentry",
  "EMS Mortar Sentry",
  "Flame Sentry",
  "Gas Mine",
  "Gatling Sentry",
  "Grenadier Battlement",
  "HMG Emplacement",
  "Incendiary Mines",
  "Laser Sentry",
  "Machine Gun Sentry",
  "Mortar Sentry",
  "Rocket Sentry",
  "Shield Generator Relay",
  "Tesla Tower"
];
